# Generated by Django 3.2.6 on 2022-02-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acivity', '0002_alter_recentactivity_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentactivity',
            name='picture',
            field=models.ImageField(upload_to='article/', verbose_name='picture'),
        ),
    ]
